<?php

/**
 * @file
 * Contains connections.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function connections_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the connections module.
    case 'help.page.connections':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides contact and social network links') . '</p>';
      return $output;

    default:
  }
}
